name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
      
    - name: Install Cloud Functions deps
      run: |
        cd cloud_functions
        npm ci
        npm test --if-present

    - name: Flutter Lint
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.19.0"
    - run: |
        cd mobile_app
        flutter pub get
        flutter analyze
